import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.getciteflow.ai';
  return [
    { url: baseUrl, lastModified: new Date('2026-05-20'), changeFrequency: 'weekly', priority: 1 },
    { url: `${baseUrl}/blog`, lastModified: new Date('2026-05-18'), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/blog/geo-guide`, lastModified: new Date('2026-05-15'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/chatgpt-seo`, lastModified: new Date('2026-05-10'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility`, lastModified: new Date('2026-05-05'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/rank-in-chatgpt`, lastModified: new Date('2026-05-18'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/what-is-geo`, lastModified: new Date('2026-05-31'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-search-vs-seo`, lastModified: new Date('2026-05-31'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/why-chatgpt-doesnt-mention-your-site`, lastModified: new Date('2026-05-24'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/geo-for-ai-tools`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/geo-for-saas`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/geo-for-startups`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/services/ai-visibility-growth`, lastModified: new Date('2026-05-25'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/case-studies`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/case-studies/nexus-protocol`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/case-studies/notion-strategy`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/blog/ai-traffic-2026`, lastModified: new Date('2026-06-18'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/eating-our-own-dog-food`, lastModified: new Date('2026-06-13'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/how-ai-chooses-sources`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/entity-gap`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/geo-vs-seo`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/schema-markup`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/build-entity-associations`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-crawler-playbook`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/comparison-content-ai-citations`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/content-structure-llm-citations`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-agent-traffic-growth`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-saas`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-ecommerce`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-startups`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-professional-services`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/block-ai-crawlers-backfire`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-overviews-changed-google-search`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-measurement`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-citations-roi`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/ai-visibility-audit`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/blog/future-search-citations-cmo`, lastModified: new Date('2026-06-22'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/compare`, lastModified: new Date('2026-05-20'), changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/compare/ahrefs-vs-getciteflow`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/compare/profound-vs-getciteflow`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/pricing`, lastModified: new Date('2026-05-20'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/privacy-policy`, lastModified: new Date('2026-05-01'), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/terms-of-service`, lastModified: new Date('2026-05-01'), changeFrequency: 'yearly', priority: 0.3 },
  ];
}
